version: '3'

services:
  mongodb:
    image: mongo:3.4
    container_name: campus-party-mongodb
    restart: always
    volumes:
    - campus-party-mongodb:/data/db/
    environment:
    - TZ=America/Sao_Paulo
    ports:
    - 27017:27017

  nodejs:
    build: .
    volumes:
      - ./server/:/usr/src/app/
    environment:
      - BD=mongodb
      - SERVICE_PORTS=3000

  lb:
    image: dockercloud/haproxy
    links:
      - nodejs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
volumes:
  campus-party-mongodb: